import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/`;

const isProd = process.argv[2] === "production";

const options = {
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "ES6",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

if (isProd) {
  await esbuild.build(options);
  process.exit(0);
} else {
  await esbuild.build({
    ...options,
    watch: {
      onRebuild(error) {
        if (error) console.error("✖ rebuild failed", error);
        else console.log("✔ rebuild succeeded");
      },
    },
  });
}
